Cache certain GitHub URLs
wp-cli/extension-command pull request #385
Opened 2023-11-16 16:53 UTC by pfefferle

Cache GitHub URLs, where we can extract the plugin/theme name and the version number.

this fixes #363

2023-12-12 23:21 UTC, danielbachhuber commented
@pfefferle Are you still planning to finish this up?

2024-01-09 11:03 UTC, pfefferle commented
Sure, but I thought it might be good to wait for https://github.com/wp-cli/extension-command/pull/386 to be merged to see if I can re-use some of its functionality?!?

2025-04-30 19:52 UTC, swissspidy approved these changes

2025-04-30 19:57 UTC, swissspidy commented
@schlessera wanna review it too since you added it to #6086?

2025-05-05 19:02 UTC, schlessera requested changes

2025-05-05 19:02 UTC, schlessera commented on features/upgradables.feature
> +      """
```suggestion
    Then STDOUT should contain:
      """
      Plugin installed successfully
      """
    And STDOUT should not contain:
      """
      Using cached file '{SUITE_CACHE_DIR}/plugin/<item>-<version>
      """
```

2025-05-05 19:02 UTC, schlessera commented on features/upgradables.feature
> +      """
```suggestion
    Then STDOUT should contain:
      """
      Plugin installed successfully
      """
    And STDOUT should contain:
      """
      Using cached file '{SUITE_CACHE_DIR}/plugin/<item>-<version>
      """
```

2025-05-05 20:10 UTC, schlessera approved these changes

2025-05-05 20:10 UTC, merged

2025-05-05 20:10 UTC, schlessera commented
Thanks for your work on this, @pfefferle !