WIP: Add support GitHub releases/latest on installation
wp-cli/extension-command pull request #386
Opened 2023-11-17 09:16 UTC by BogdanUngureanu

Related to https://github.com/wp-cli/extension-command/issues/91

This PR adds support for installing plugins and themes from GitHub using the `release/latest` URLs.

In order to get the latest release assets, I'm proposing to use the GitHub public API to extract the latest version of the plugin/theme from GH releases. If there's no asset defined, we will fall back to the source code zip file.

While the implementation works right now, I haven't added support for GitHub's API request limits. Currently, after 60 requests per hour, the user is required to use an access token in order to make an API request. However, this PR doesn't expose a way to pass that token to the request.

To fix this problem, I've come up with two alternative approaches:
- Pass a new optional GitHub access token as a flag on the command. 
- Use the `gh` CLI to make the requests to github. The `gh` tool should have the access token configured. However, I'm not in favor of this because will introduce an external dependency to WP-Cli, which is not transparent enough.

Personally, I would go for the first option since the current implementation already uses an HTTP request.

2023-11-17 10:46 UTC, swissspidy commented
> * Pass a new optional GitHub access token as a flag on the command.

I'd use an environment variable instead, e.g. `getenv( 'GITHUB_TOKEN' )`

2023-11-18 13:56 UTC, BogdanUngureanu commented
Hey @swissspidy, that's a great idea! I've updated the PR to contain the environment variable you proposed. Thanks!

2023-12-08 22:30 UTC, danielbachhuber requested changes
Looks like a great start, @BogdanUngureanu ! I have a few changes to suggest.

2023-12-08 22:30 UTC, danielbachhuber commented on src/WP_CLI/ParseGithubUrlInput.php
> +	public function get_github_repo_from_url( $url ) {
```suggestion
	public function get_github_repo_from_releases_url( $url ) {
```

Should we include 'releases' in this method name to make it more specific?

2023-12-08 22:30 UTC, danielbachhuber commented on src/WP_CLI/ParseGithubUrlInput.php
> +final class ParseGithubUrlInput {
Can we move the methods on this class to the existing `CommandWithUpgrade` class? I don't think we want to introduce it as a class others can use, etc.

2023-12-08 22:30 UTC, danielbachhuber commented on features/plugin-install-github-latest.feature
> +      """
Can you include a test case for the non-happy path too?

2024-04-26 21:03 UTC, swissspidy commented
Closing in favor of #421

2024-04-26 21:03 UTC, closed without merging